### ISSUE TITLE
ACR122U-A9, MacOS 10.13.6, CIE middleware 1.1 - Errore inaspettato durante la comunicazione con la smart card

### ISSUE THREAD

**Issue by finzic** [italia/cie-middleware-macos#18]
Installando CIE middleware 1.1 su sistema MacOS 10.13.6 con lettore ACR122U-A9 ottengo l'errore indicato nel titolo (Errore inaspettato durante la comunicazione con la smart card) e a log rilevo i seguenti messaggi ogni volta che appoggio la card sul lettore: 

> default	23:14:30.393492 +0200	securityd	reader ACS ACR122U: state changed 16 -> 34

> default	23:14:30.395357 +0200	securityd	MacOS error: -25337
> default	23:14:30.398228 +0200	securityd	CSSM Exception: 229 unknown error 229=e5
> default	23:14:30.399461 +0200	securityd	token in reader ACS ACR122U cannot be used (error 229)
> default	23:14:30.399712 +0200	securityd	MacOS error: -25337
> default	23:14:30.401513 +0200	securityd	CSSM Exception: 229 unknown error 229=e5
> default	23:14:30.423988 +0200	pkd	plugin /Applications/CIE ID.app/Contents/PlugIns/CIEToken.appex is still valid.
> default	23:14:30.424211 +0200	pkd	plugin /System/Library/Frameworks/CryptoTokenKit.framework/PlugIns/pivtoken.appex is still valid.
> default	23:14:30.558766 +0200	pkd	plugin /Applications/CIE ID.app/Contents/PlugIns/CIEToken.appex is still valid.
> default	23:14:30.559525 +0200	pkd	allowing host 430 <private> to use plug-in <private>(<private>) uuid=7EE2F435-099D-4191-A777-2E8CABAAA9B2 at <private>
> default	23:14:30.621009 +0200	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
> default	23:14:30.668428 +0200	ctkd	it.ipzs.CIE-ID.CIEToken cannot handle token in slot ACS ACR122U, error:(null)
> error	23:14:30.670174 +0200	ctkd	No token driver found for card <TKSmartCardATR: 0x7f9428b03ec0 3b --- T=0:--- T=1:---;8031806549544e5850120fffffff> ATR bytes: <3b8e8001 80318065 49544e58 50120fff ffffe2>
> default	23:14:30.737764 +0200	securityd	reader ACS ACR122U: state changed 32 -> 290
> default	23:14:30.739812 +0200	securityd	MacOS error: -25337
> default	23:14:30.741872 +0200	securityd	CSSM Exception: 229 unknown error 229=e5
> default	23:14:30.743355 +0200	securityd	token in reader ACS ACR122U cannot be used (error 229)
> default	23:14:30.743709 +0200	securityd	MacOS error: -25337
> default	23:14:30.745802 +0200	securityd	CSSM Exception: 229 unknown error 229=e5
> error	23:14:30.752676 +0200	CIEToken	failed to create token in slot ACS ACR122U (AID:(null), error:Error Domain=CIEToken Code=101 "Middleware's getSlotList fails'" UserInfo={NSLocalizedDescription=Middleware's getSlotList fails'})
> default	23:14:30.752453 +0200	securityd	reader ACS ACR122U: state changed 288 -> 34
> default	23:14:30.757578 +0200	securityd	MacOS error: -25337
> default	23:14:30.758995 +0200	securityd	CSSM Exception: 229 unknown error 229=e5
> default	23:14:30.759612 +0200	securityd	token in reader ACS ACR122U cannot be used (error 229)
> default	23:14:30.759759 +0200	securityd	MacOS error: -25337
> default	23:14:30.761098 +0200	securityd	CSSM Exception: 229 unknown error 229=e5`
>

A disposizione per chiarimenti

**Comment by MatFerry** [comment]
Stessa mia condizione. Sei riuscito a far qualcosa?

**Comment by finzic** [comment]
Fino all'altro giorno ho abbandonato la questione perchèé avevo pure
provato io a ricompilare il tutto, ma ... dipendenze verso branch MASTER di
pacchetti open-source che nel frattempo erano evoluti impedivano la
compilazione.
Ora ho notato sul sito del produttore di ACR122U che è disponibile un nuovo
driver datato January 2020, quindi appena possibile proverò ad installare
quello e vedere se vi si riesce a concludere qualcosa :)


Il giorno sab 15 feb 2020 alle ore 12:19 MatFerry <notifications@github.com>
ha scritto:

**Comment by marcopapale** [comment]
Qualcuno ha aggiornamenti riguardo il firmware di Gennaio? 
Io l'ho installato e continua a darmi errore inaspettato durante la comunicazione con la carta. 

Mac OS 10.14.6
Lettore ACR122U-A9

**Comment by ugochirico** [comment]
come ho già spiegato in [#8] questo problema è specifico di alcuni lotti di lettori ACS ACR122U.
Tali lettori hanno un bug nel firmware che manda il driver in timeout mentre la CIE sta eseguendo la procedura di mutua autenticazione tra chip e host. Tale procedura prevede l'esecuzione di una firma digitale RSA da parte del chip e pertanto richiede un tempo non trascurabile che supera il valore del timeout impostato nel firmware.
Il lettore sembra funzionare con altri tipi di smart card perchè queste non eseguono alcuna operazione di mutua autenticazione con RSA.
Il firmware degli ACR122U non è aggiornabile e aggiornare i driver non serve a nulla.

**Comment by danielearrighi** [comment]
Ciao,
Ho acquistato il lettore in questione e sto avendo lo stesso problema qui indicato. Praticamente ho buttato i soldi?

**Comment by ugochirico** [comment]
@danielearrighi  Dove lo hai comprato? 
Così almeno iniziamo a capire dove non comprarlo.

Quel lettore non funziona con la CIE ma funziona con tutte le altre card RFID/NFC. Se lo avevi acquistato esclusivamente per la CIE allora si, hai buttato i soldi. Prova a restituirlo.

**Comment by marcopapale** [comment]
Purtroppo è uno dei lettori più venduti su Amazon e le recensioni sono fuorvianti perchè molti utenti scrivono che funziona con CIE.
@ugochirico Io dopo il tuo messaggio l'ho restituito e sostituito con il **REINERSCT Cyber Jack® RFID basis** che non soltanto è più carino esteticamente, ma ha funzionato al primo colpo senza dover installare niente di aggiuntivo. Il prezzo è allineato siamo sui 40€ Lo riconoscete perche nell'immagine del prodotto c'è una CIE Tedesca.

**Comment by finzic** [comment]
Io sono riuscito a far funzionare il lettore in questione ACR122U
pochissime volte. In particolare con W10 ho notato che sono riuscito a fare
l'autenticazione sul sito INPS solamente attaccandolo ad una presa USB
direttamente onboard, e non alle 'prolunghe' sul frontale del case. In ogni
caso il riconoscimento è abbastanza scadente e non dà garanzia di
stabilità... spero di non aver gettato i soldi al vento...

Il sab 14 mar 2020, 18:42 Daniele <notifications@github.com> ha scritto:

**Comment by danielearrighi** [comment]
> @danielearrighi Dove lo hai comprato?
> Così almeno iniziamo a capire dove non comprarlo.
> 
Ebay (venditore UK) spedito dalla cina. Proverò a restituirlo. Grazie.

**Comment by stevestasi** [comment]
@ugochirico ho avuto lo stesso problema su un ACR122U preso da Amazon e appena restituito. Fatto da ACS (https://www.acs.com.hk) Marcato KKMOON (https://www.kkmoon.com/p-h10391.html).
Sapete consigliare un lettore di smart card che funzioni sicuramente con CIE sul Mac?

**Comment by psychotrain65** [comment]
@stevestasi Riapro per segnalare lo stesso problema con lo stesso lettore. Ma ho scoperto anche che tutto dipende dalla porta usb. Funziona correttamente su usb 2.0, non su usb 3.x, dove va in timeout. Testato anche con linux (pacchetto .deb) e con Windows 10.

**Comment by k133** [comment]
Pare che per risolvere il problema del timeout, bisogna inviare un comando APDU (ad esempio con GlobalPlatformPro) al lettore, il quale intercetterà questo comando e imposterà il timeout per attendere la risposta di una smart card.
Il comando sarebbe: APDU 0xFF0041FF00h
Non ho la più pallida idea cosa voglia dire e come eseguire il tale comando.
Fonte: https://forum.dangerousthings.com/t/fix-for-acr122u-time-extension/5489 utente: "fraggersparks"

> come ho già spiegato in [#8] questo problema è specifico di alcuni lotti di lettori ACS ACR122U. Tali lettori hanno un bug nel firmware che manda il driver in timeout mentre la CIE sta eseguendo la procedura di mutua autenticazione tra chip e host. Tale procedura prevede l'esecuzione di una firma digitale RSA da parte del chip e pertanto richiede un tempo non trascurabile che supera il valore del timeout impostato nel firmware. Il lettore sembra funzionare con altri tipi di smart card perchè queste non eseguono alcuna operazione di mutua autenticazione con RSA. Il firmware degli ACR122U non è aggiornabile e aggiornare i driver non serve a nulla.

**Comment by 00sapo** [comment]
Copio incollo da https://github.com/italia/cie-middleware-macos/issues/8

Possiedo ACR122U con firmware 2.14, il più recente, che sembrerebbe quindi non possedere il problema citato da @ugochirico. Il problema è che ccid non supporta perfettamente questo lettore. Esistono alcune patch per pcsclite, ma non ho ancora avuto tempo di provarle.

Il problema, al contrario di quanto scritto sopra, è a livello driver, o almeno può anche essere a quel livello su sitemi Linux (e ipotizzo anche sistemi Mac). Nemmeno l'istruzione APDU citata sopra, e reperibile nel manuale ufficiale di ACR122U, funziona. Se qualcuno volesse provare, basta usare il comando echo FF00411000 | scriptor dopo avere appoggiato la carta sul sensore. Necessario il pacchetto pcsc-tools. Il comando non dovrebbe essere persistente a scollegamenti/ricollegamenti del sensore.

Ho provato con windows su virtual machine kvm, driver 4.2.8.0 (l'ultimo) e funziona perfettamente con il middleware CIE.

**Comment by k133** [comment]
Non è colpa del lettore. Ho cambiato Pc e funziona perfettamente. Sarà dovuto alla porta usb 3.1 Gen 1?

**Comment by p060477** [comment]
Salve, stesso problema ma con win 10 home 64
non riesco ad usare la CIE ottengo sempre questo errore , che vi allego,
quando tento di abbinare la carta
ho un lettore smart card NFC  iso 14443
questo:
https://www.trust.com/it/product/24736-ceto-contactless-smartcard-reader#faq
che è compatibile con i dati tecnici della CIE 3.0 in mio possesso

https://www.cartaidentita.interno.gov.it/downloads/2021/03/cie_3.0_-_specifiche_chip.pdf

cosa devo fare?
ho un pc windows 10 home 64 e il programma governativo per la CIE:
CIE-Middleware-1.4.3-4 installato

grazie in anticipo per l'attenzione e per aver sollevato il problema
