### ISSUE TITLE
Errore di build - repo OpenSSL apparentemente spostato

### ISSUE THREAD

**Issue by finzic** [italia/cie-middleware-macos#19]
Salve, 
tentando di compilare su MacOS il progetto ottengo il seguente errore - apparentemente il repository per OpenSSL è stato spostato. 

> [finzik@legolas /Volumes/TeraFireCUDA/progs/git/cie-middleware-macos (master)]$ pod install
> Analyzing dependencies
> Downloading dependencies
> Installing OpenSSL-Static (1.0.2.c1)
> Username for 'https://github.com': finzic
> Password for 'https://finzic@github.com': 
> 
> [!] Error installing OpenSSL-Static
> [!] /opt/local/bin/git clone https://github.com/bruceyibin/OpenSSL.git /var/folders/q5/kxv9b9n90ll_6pp2wnm8cx1c0000gn/T/d20190904-1242-gbxyce --template= --single-branch --depth 1 --branch 1.0.2.c1
> 
> Cloning into '/var/folders/q5/kxv9b9n90ll_6pp2wnm8cx1c0000gn/T/d20190904-1242-gbxyce'...
> remote: Repository not found.
> fatal: repository 'https://github.com/bruceyibin/OpenSSL.git/' not found
> 
> [finzik@legolas /Volumes/TeraFireCUDA/progs/git/cie-middleware-macos (master)]$

**Comment by ebrienza** [comment]
Stesso problema
