### ISSUE TITLE
Impossibile aprire “CIE-Middleware-v1.3.pkg” - macOS 10.15.1

### ISSUE THREAD

**Issue by ingbilly71** [italia/cie-middleware-macos#20]
Impossibile aprire “CIE-Middleware-v1.3.pkg” perché Apple non può verificare la presenza di malware.
Ritengo che l'errore sia connesso con la presenza di software a 32 bit, incompatibile con la versione Catalina.
<img width="451" alt="Schermata 2019-11-03 alle 12 15 46" src="https://user-images.githubusercontent.com/57316634/68084262-b1209300-fe33-11e9-94a4-c542ef9eba67.png">

**Comment by ebrienza** [comment]
Grazie per la segnalazione, approfondiremo.

**Comment by ebrienza** [comment]
Come workaround, in attesa di trovare una soluzione, è possibile procedere con l'installazione facendo tasto destro -> Apri.

**Comment by ingbilly71** [comment]
Grazie, così si è installata

**Comment by ebrienza** [comment]
Il problema è stato risolto pubblicando un nuovo package di installazione sul sito. 
Grazie ancora per la segnalazione.
Provvedo a chiudere la issue.
