### ISSUE TITLE
Verifica del PIN con componente Cryptotokenkit in ambiente MacOS 10.15 (Catalina)

### ISSUE THREAD

**Issue by aantetomaso** [italia/cie-middleware-macos#23]
In ambiente MacOS Catalina, capita randomicamente che, in fase di autenticazione, il browser sia impossibilitato a verificare il PIN, bloccandolo dopo il terzo tentativo e rendendo necessario lo sblocco mediante PUK.
Succede con i browser che si servono dell'interfaccia Cryptotokenkit. 
Con Firefox e interfaccia PKCS#11 non capita.

**Comment by ugochirico** [comment]
Corretto nella versione 1.3.1
