### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by aantetomaso** [italia/cie-middleware-macos#26]
È necessario gestire la modalità "Dark" delle schermate dell'app CIE ID e di quelle per la verifica del PIN fornite dal Software CIE.

**Comment by matteodelv** [comment]
In aggiunta, ci sarebbe da sistema l'icona nella nav bar. Utilizzo un Mac in Dark mode; quando CIE ID Bar, suppongo, è in esecuzione, l'icona non è visibile, risultando in uno spazio vuoto. Nel momento in cui si clicca tale spazio, l'icona riappare.  
  
![image](https://i.ibb.co/C2tgnmk/Schermata-2020-05-01-alle-11-13-16.png)  
  
![image](https://i.ibb.co/prPdv7h/Schermata-2020-05-01-alle-11-13-08.png)

**Comment by aantetomaso** [comment]
Risolta nella 1.4.3.9
