### ISSUE TITLE
Problema con lettori multipli

### ISSUE THREAD

**Issue by jkumeboshi** [italia/cie-middleware-macos#29]
Quando sono collegati più lettori al Mac, l'autenticazione con Safari funziona solamente se il lettore che contiene la CIE è il primo della lista restituita dal comando eseguito al terminale:
#> pcsctest
Reader 01: ACS ACR38U 0
Reader 02: ACS ACR1255U-J1 0

i casi sono questi:
1) Se c'è un solo lettore contactless collegato, funziona.
2) Se ci sono 2 lettori collegati ed il lettore contactless appare come "Reader 01" funziona.
3) Se ci sono 2 lettori collegati ed il lettore contactless appare come "Reader 02", non funziona.
4) Se c'è un solo lettore collegato, ma è un lettore DUALE (con 2 slot, uno di interfaccia contactless ed uno contact) de l'interfaccia contactless appare come "Reader 02", non funziona.

Il caso 4 è un grosso problema perché mentre nel caso 3 posso decidere di non collegare temporaneamente i lettore a contatto, nel caso 4 non ho scelta.

Provando a contattare il produttore del lettore DUAL mi hanno dimostrato che il lettore funziona perfettamente, ad esempio usando Firefox e la libreria libcie-pkcs11.dylib, tra l'altro operazione per niente agevole da mettere in atto (devo cambiare browser, devo fare una configurazione non proprio facile da trovare e mettere in atto!), e che dunque il problema risiede nel middleware CIE.

**Comment by aantetomaso** [comment]
Fixed in release 1.3.2
