### ISSUE TITLE
Su macOS Mojave

### ISSUE THREAD

**Issue by fiorins** [italia/cie-middleware-macos#30]
Risulta non funzionante sul mio os come si può vedere in video quando lo apro si chiude immediatamente

![cie-id](https://user-images.githubusercontent.com/32281481/97144526-e5881000-1764-11eb-80ff-d2aceae8a9b2.gif)

**Comment by jabberabbe** [comment]
Osservo lo stesso bug sempre su Mojave. Rende completamente inutilizzabile il middleware poiché non è possibile abbinare la CIE...
Magari se l'interfaccia grafica richiede molto lavoro è sufficiente un eseguibile a linea di comando temporaneamente, ma così è totalmente inutile l'intero pacchetto software.

**Comment by aantetomaso** [comment]
Risolta nella versione 1.4.2

**Comment by ClaudiaRaffaelli** [comment]
Riapro la issue perché riscontro lo stesso problema nella versione 1.4.3.1 su macOS Monterey v12.2.1. Confermo invece che la versione del software 1.4.2 funziona correttamente.
