### ISSUE TITLE
software CIE 1.4.1 si chiude inaspettatamente durante procedura di abbinamento con MAC OS 11.15.1

### ISSUE THREAD

**Issue by ferdinandobelmonte** [italia/cie-middleware-macos#39]
Mentre si procede all'abbinamento la applicazione si chiude

Attach #:0
Process:               CIE ID [928]
Path:                  /Applications/CIE ID.app/Contents/MacOS/CIE ID
Identifier:            it.ipzs.CIE-ID
Version:               1.4.1 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CIE ID [928]
User ID:               501

Date/Time:             2021-08-09 13:28:55.774 +0200
OS Version:            macOS 11.5.1 (20G80)
Report Version:        12
Bridge OS Version:     5.5 (18P4759a)
Anonymous UUID:        0D2B9A54-0E07-AB81-5C11-BC1D266AEB88

Time Awake Since Boot: 440 seconds

System Integrity Protection: enabled

Crashed Thread:        3  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type windows_error
abort() called

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib         0x00007fff2045d2ba mach_msg_trap + 10
1   libsystem_kernel.dylib         0x00007fff2045d62c mach_msg + 60
2   com.apple.CoreFoundation       0x00007fff2058bb2f
__CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation       0x00007fff2058a20f __CFRunLoopRun + 1328
4   com.apple.CoreFoundation       0x00007fff2058961c CFRunLoopRunSpecific
+ 563
5   com.apple.HIToolbox           0x00007fff287cea83
RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           0x00007fff287ce7e5 ReceiveNextEventCommon
+ 587
7   com.apple.HIToolbox           0x00007fff287ce583
_BlockUntilNextEventMatchingListInModeWithFilter + 70
8   com.apple.AppKit               0x00007fff22d90502 _DPSNextEvent + 864
9   com.apple.AppKit               0x00007fff22d8ecd5
-[NSApplication(NSEvent)
_nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
10  com.apple.AppKit               0x00007fff22d81049 -[NSApplication run]
+ 586
11  com.apple.AppKit               0x00007fff22d5524c NSApplicationMain +
816
12  libdyld.dylib                 0x00007fff204adf3d start + 1

Thread 1:: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib         0x00007fff2045fcde __psynch_cvwait + 10
1   libsystem_pthread.dylib       0x00007fff20492e49 _pthread_cond_wait +
1298
2   libc++.1.dylib                 0x00007fff203fbd72
std::__1::condition_variable::wait(std::__1::unique_lock&)
+ 18
3   com.apple.JavaScriptCore       0x00007fff37585934 void
std::__1::condition_variable_any::wait
(std::__1::unique_lock&) + 84
4   com.apple.JavaScriptCore       0x00007fff3758a3fb
bmalloc::Scavenger::threadRunLoop() + 331
5   com.apple.JavaScriptCore       0x00007fff37589f89
bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 9
6   com.apple.JavaScriptCore       0x00007fff3758cb17 void*
std::__1::__thread_proxy >, void
(*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 39
7   libsystem_pthread.dylib       0x00007fff204928fc _pthread_start + 224
8   libsystem_pthread.dylib       0x00007fff2048e443 thread_start + 15

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib         0x00007fff2045d2ba mach_msg_trap + 10
1   libsystem_kernel.dylib         0

**Comment by aantetomaso** [comment]
risolto nella 1.4.2
