### ISSUE TITLE
Firma Grafica non funzionante

### ISSUE THREAD

**Issue by tamamma** [italia/cie-middleware-macos#59]
Ci sono problemi con la firma grafica, quella custom attraverso il caricamento di un PNG.
Il PNG in questione ha il canale alfa come suggerito.
Quando viene generata la firma con il middleware CIE-ID (OSX Ventura ma anche su Sonoma) esce un blocco nero, sia se apro il PDF firmato con Adobe che con Anteprima.
Inoltre non è possibile visualizzare la versione software attuale in CIEID nè c'è la possibilità di verificare ed eventualmente installare nuovi aggiornamenti. L'unica opzione possibile è "Chiudi CIE ID"

Inoltre come enanchment sarebbe utile portare il focus del mouse direttamente sui campi in cui inserire il PIN quando ci si trova in tale step per apporre la firma digitale.

**Comment by aantetomaso** [comment]
Risolta nella 1.4.3.9
