### ISSUE TITLE
CIE ID versione App Store

### ISSUE THREAD

**Issue by RiccardoSaettone** [italia/cie-middleware-macos#61]
Salve

Ho un problema con la nuova versione del software CIE ID, quella che si scarica direttamente dall’ App Store.
Ho cancellato la vecchia versione riavviato, installato quella nuova, ed avviato di nuovo.
Con la versione precedente non avevo alcun problema, ma con questa nuova versione non riesco a completare l’abbinamento, metto la CIE sul lettore REINERS SCT inserisco tutte le 8 cifre del PIN l’app comincia la procedura di abbinamento, ma quando arriva alla fase “autenticazione”, l’app si chiude senza generare alcun errore.

Mac Studio Apple Silicon M1 pro Max
macOS: Sonoma 14.4.1

Ecco il file di Log creato con livello debug 
[CIEPKI_2024-04-13.log](https://github.com/italia/cie-middleware-macos/files/14968614/CIEPKI_2024-04-13.log)

Per favore potreste spostare il file di log in una posizione leggermente più intuitiva, ma sopratutto più comoda, per gli utenti meno esperti.
Attualmente il file di log viene creato in /Users/[NOMEUTENTE]/Library/Containers/it.ipzs.SoftwareCIE.CIEToken/Data/.CIEPKI/
Che anche se scritto sul manuale, non è proprio il posto più intuitivo dove andarlo a cercare.
Senza contare che nel manuale è scritto che si trova in "./Library/Containers/it.ipzs.CIE-ID.CIEIDToken/Data/.CIEPKI." un utente esperto ci arriva ma uno normale no.

Il vero problema però è che la cartella ".CIEPKI" avendo il punto come primo carattere risulta invisibile dal finder, quindi per aprirla bisogna prima arrivarci tramite il terminale, copiarsi tutto il path e infine dal finder usare il comando vai a cartella e ricopiare tutto il path.
Come ho detto per un utente mediamente esperto non ci sono problemi, ma per un utente normale può essere difficile arrivare a quel file.
La soluzione migliore sarebbe aver un pulsante nell'app CIE per apre direttamente la cartella dove si trova il file di log, e magari spostare il file di log in un posto più consono tipo /Users/[NOMEUTENTE]/Library/Logs

**Comment by RiccardoSaettone** [comment]
Una richiesta potreste spostare il file di log in una posizione leggermente più intuitiva, ma sopratutto comoda, soprautto per gli utenti meno esperti.
Attualmente viene creato in /Users/[NOMEUTENTE]/Library/Containers/it.ipzs.SoftwareCIE.CIEToken/Data/.CIEPKI/
Che anche se scritto sul manuale, non è proprio il posto più intuitivo, senza contare che nel manuale è scritto che si trova in "./Library/Containers/it.ipzs.CIE-ID.CIEIDToken/Data/.CIEPKI."

Ma il vero problema è che la cartella ".CIEPKI" avendo il punto come primo carattere risulta invisibile se si prova ad arrivarci tramite il finder, quindi per arrivarci bisogna prima arrivarci tramite il terminale, copiarsi tutto il path e infine dal finder usare il comando vaia cartella e ricopiare tutto il path.
Per un utente mediamente esperto non ci sono problemi, ma per un utente normale può essere difficile arrivare a quel file.
La soluzione migliore sarebbe aver un pulsante nell'app CIE per apre direttamente la cartella dove si trova il file di log, e magari spostare il file di log in un posto più consono tipo /Users/[NOMEUTENTE]/Library/Logs

**Comment by aantetomaso** [comment]
Grazie della segnalazione, indaghiamo. In merito alla gestione dei log, apro un'altra issues di tipo "enhancement". Si pensava di realizzare magari una funzione di estrazione dei file di log in un archivio pronto all'uso, direttamente dall'applicazione CIE ID.

**Comment by aantetomaso** [comment]
Grazie del supporto, terminata l’analisi verrà probabilmente contattato per approfondimenti. Intanto, trattandosi di processore ARM, potrebbe confermare di avere Rosetta installato? Il Software CIE non è ancora disponibile come nativo per processori della serie M. Su di essi funziona correttamente in modalità compatibilità, a patto di avere il software Rosetta di Apple installato. Puoi farci sapere?

**Comment by RiccardoSaettone** [comment]
> Il Software CIE non è ancora disponibile come nativo per processori della serie M. Su di essi funziona correttamente in modalità compatibilità, a patto di avere il software Rosetta di Apple installato. Puoi farci sapere?

Si ho rosetta installato e funzionante, la prova è che posso aprire altre app come ad esempio safari in "modalità" rosetta (informazioni su file e seleziono apri usando Rosetta).

**Comment by aantetomaso** [comment]
OK grazie, aggiornamenti appena possibile.

**Comment by AntonioCiccarelli** [comment]
Buongiorno Riccardo,
potresti contattarci all'indirizzo e-mail cieid@bit4id.com? Potrebbe essere necessario effettuare una sessione di assistenza da remoto per diagnosticare la problematica riscontrata.

Grazie.

**Comment by RiccardoSaettone** [comment]
> Buongiorno Riccardo, potresti contattarci all'indirizzo e-mail [cieid@bit4id.com](mailto:cieid@bit4id.com)? Potrebbe essere necessario effettuare una sessione di assistenza da remoto per diagnosticare la problematica riscontrata.

Si certo nel pomeriggio vi scrivo.

**Comment by RiccardoSaettone** [comment]
Dopo un bel po' di prove posso dire che il problema è nel lettore Reiner-SCT cyberJack® RFID basis, non la versione attualmente venduta ma quella vecchia.

Questa è la nuova versione del lettore che funziona regolarmente
![cyberJack_RFID_basis_Nuova versione](https://github.com/italia/cie-middleware-macos/assets/25837738/297f47a5-8bfc-4f47-a2cf-c579abae3d96)

Questa è la vecchia versione versione che non funziona.
![cyberJack_RFID_basis_Vecchia_versione](https://github.com/italia/cie-middleware-macos/assets/25837738/c5d9f2f8-6266-43da-9541-0136e69e9082)

**Comment by aantetomaso** [comment]
Grazie mille.
