### ISSUE TITLE
Problema con lettore ACR122U

### ISSUE THREAD

**Issue by ebrienza** [italia/cie-middleware-macos#8]
Non è possibile eseguire la lettura della carta con lettore ACS ACR122U nonostante i driver siano stati scaricati direttamente dal sito del produttore. 
Durante la registrazione della CIE viene mostrato il seguente errore: "Errore inaspettato durante la comunicazione con la smart card".
Il test è stato eseguito su macOS 10.12.6

**Comment by mscolly** [comment]
Ho lo stesso problema con macOS 10.14.
Non so se centra, ma nfc-list mi dà l'errore nello screenshot:
![nfc-list-error](https://user-images.githubusercontent.com/2337508/54489536-96ea7280-48ad-11e9-82da-b45851e349e8.png)

**Comment by alexit84** [comment]
Avevo un problema simile, poi risolto reinstallando i driver del lettore, come riportato qua: [https://github.com/italia/cie-middleware-macos/issues/5#issuecomment-446405431](url). Avete eseguito questo passaggio?

**Comment by DanRom624** [comment]
Ho lo stesso problema di **ebrienza**.
Ho disistallato e reinstallato i driver come suggerito da **alexit84**, _il problema persiste_ .
Tuttavia, la app "NFC Tools" legge e scrive regolarmente sulle smartcard in bianco pervenutemi a corredo del lettore. (La app è scaricabile da AppStore https://apps.apple.com/it/app/nfc-tools/id1252962749). Ne deduco, ma potrei sbagliarmi, che il problema risieda nell'applicativo "CieID"
Sistema operativo: macOS 10.15.2 (Catalina)
Lettore: KKMOON ACR122U-A9

**Comment by ugochirico** [comment]
Il problema è specifico di alcuni lotti di lettori ACS ACR122U.
Tali lettori hanno un bug nel firmware che manda il driver in timeout mentre la CIE sta eseguendo la procedura di mutua autenticazione tra chip e host. Tale procedura prevede l'esecuzione di una firma digitale RSA da parte del chip e pertanto richiede un tempo non trascurabile che supera il valore del timeout impostato nel firmware. 
Il lettore sembra funzionare con altri tipi di smart card perchè queste non eseguono alcuna operazione di mutua autenticazione con RSA.

**Comment by stevestasi** [comment]
Buongiorno a tutti. Qualcuno sa consigliare un lettore per CIE che funzioni bene con il Mac?
Grazie mille in anticipo

**Comment by ebbre** [comment]
> 
> 
> Il problema è specifico di alcuni lotti di lettori ACS ACR122U.
> Tali lettori hanno un bug nel firmware che manda il driver in timeout mentre la CIE sta eseguendo la procedura di mutua autenticazione tra chip e host. Tale procedura prevede l'esecuzione di una firma digitale RSA da parte del chip e pertanto richiede un tempo non trascurabile che supera il valore del timeout impostato nel firmware.
> Il lettore sembra funzionare con altri tipi di smart card perchè queste non eseguono alcuna operazione di mutua autenticazione con RSA.

Ciao @ugochirico,
hai un riferimento riguardo ai lotti di ACR122U difettosi?

**Comment by ebbre** [comment]
Buongiorno a tutti,
segnalo che ho testato con successo diversi lettori contactless prodotti da Identiv.
Più precisamente, ho testato i seguenti modelli:
- uTrust 3700F
- uTrust 3720F HF Multi-ISO
- uTrust 3720F HF+LF
- uTrust 4701F
- SCL3711

Testati su Windows 10. Tutti molto veloci, non hanno dato nessun problema.

**Comment by mdesalvo** [comment]
@ebbre a me **uTrust 3700F** su Windows 10 20H2 non funziona. Si inchioda alla fase di lettura del certificato con il messaggio dell'errore di comunicazione inaspettato.

**Comment by lucafont2** [comment]
Salve scrivo questo post in quanto penso che in tanti stiano avendo un problema che non esiste, ma il quale è solo un problema di fondo di come è progettato questo lettore. Io pensavo di avere il lettore difettoso, il problema sembra effettivamente essere un timeout ma in realtà non è così.  

Non sono un esperto quindi  potrei star dicendo cazzate, ma questa è la storia: 
-Avevo già questo lettore nfc in ufficio per impostare i tag di accesso e quando provavo ad usarlo per la cie ottenevo effettivamente un errore in timeout. Mi sono fatto lo spid alla fine quindi non sono andato a perdere ulteriore tempo.
-2 giorni fa ho bisogno di acquistare un secondo lettore, identico, e "certificato" per la cie, stesso problema. 

A questo punto contatto il mio amico e mi da un consiglio vitale. Cioè di mettere la carta sul lettore in orizzontale. E ora funziona perfettamente sia con il vecchio che con quello appena comprato. 

Normalmente verrebbe da metterlo in queste posizioni: 
![immagine](https://user-images.githubusercontent.com/62725689/146060506-c8ab3f34-4e09-4c07-8c8a-97c3993a858d.png)

In realtà, evidentemente visto che le posizioni di contatto degli nfc non sono le stesse rispetto allo standard (PRESUMO?) se si mette la cara in QUESTA ESATTA POSIZIONE, funziona perfettamente. 

![immagine](https://user-images.githubusercontent.com/62725689/146060792-457a471a-8f3e-4a2a-80ef-622a1fce031b.png)

Sono curioso di sapere se è stato un caso o anche agli altri con lo stesso problema questo funzioni.

Manderò questo post anche sul forum italia per vedere se questa teoria è corretta

**Comment by 00sapo** [comment]
Possiedo ACR122U con firmware 2.14, il più recente, che sembrerebbe quindi non possedere il problema citato da @ugochirico. Il problema è che `ccid` (non supporta)(https://ccid.apdu.fr/ccid/unsupported.html) perfettamente questo lettore. Esistono alcune patch per `pcsclite`, ma non ho ancora avuto tempo di porvarle. 

Il problema, al contrario di quanto scritto sopra, *è* a livello driver, o almeno può anche essere a quel livello su sitemi Linux (e ipotizzo anche sistemi Mac). Nemmeno l'istruzione APDU citata sopra, e reperibile nel manuale ufficiale di ACR122U, funziona. Se qualcuno volesse provare, basta usare il comando `echo FF00411000 | scriptor` dopo avere appoggiato la carta sul sensore. Necessario il pacchetto [pcsc-tools](https://pkgs.org/search/?q=pcsc-tools). Il comando non dovrebbe essere persistente a scollegamenti/ricollegamenti del sensore. 

Ho provato con windows su virtual machine kvm, driver 4.2.8.0 (l'ultimo) e funziona perfettamente con il middleware CIE.

**Comment by antoniomavaro** [comment]
Sono bloccato anche io col medesimo problema di lettura. Eppure la prima CIE sono riuscita ad aggiungerla, ho dovuto solo trovare la giusta posizione "in sospensione" per farmi leggere la CIE dal lettore. L'errore di comunicazione me lo sta dando nell'operazione di aggiunta di una CIE nel software CIE ID.

**Comment by nickles-lee** [comment]
Sto solo lasciando qui alcune scoperte:

* Windows identifica la CIE come una smart card con il middleware CIE installato, senza i driver ACR122U.

* L'applicazione CIE di MacOS trova la carta, ma non la espone come Smart Card/Cert al resto del sistema operativo. Ciò si verifica con o senza i driver ACR122U.

**Comment by Nikus63** [comment]
> Salve scrivo questo post in quanto penso che in tanti stiano avendo un problema che non è di tipo hardware, ma di come è progettato questo lettore. Io pensavo di avere il lettore difettoso, il problema sembra effettivamente essere un timeout ma in realtà non è così.
> 
> Non sono un esperto quindi potrei star dicendo cazzate, ma questa è la storia: -Avevo già questo lettore nfc in ufficio per impostare i tag di accesso e quando provavo ad usarlo per la cie ottenevo effettivamente un errore in timeout con relativo popup sull'app. Mi sono fatto lo spid, e alla fine non sono andato a perdere ulteriore tempo. -2 giorni fa ho avuto bisogno di acquistare un secondo lettore, identico, e "certificato" per la cie, stesso problema.
> 
> A questo punto contatto il mio amico e mi da un consiglio vitale. Cioè di mettere la carta sul lettore in orizzontale. E ora funziona perfettamente sia con il vecchio che con quello appena comprato.
> 
> Normalmente verrebbe da metterlo in queste posizioni: ![immagine](https://user-images.githubusercontent.com/62725689/146060506-c8ab3f34-4e09-4c07-8c8a-97c3993a858d.png)
> 
> In realtà, visto che le posizioni di contatto degli nfc non sono le stesse rispetto allo standard (PRESUMO) se si mette la cara in QUESTA ESATTA POSIZIONE, funziona perfettamente.
> 
> ![immagine](https://user-images.githubusercontent.com/62725689/146060792-457a471a-8f3e-4a2a-80ef-622a1fce031b.png)
> 
> Sono curioso di sapere se è stato un caso o anche agli altri con lo stesso problema questo trucco funzioni.

HA funzionato grazie mille

**Comment by usegitlab** [comment]
> Salve scrivo questo post in quanto penso che in tanti stiano avendo un problema che non è di tipo hardware, ma di come è progettato questo lettore. Io pensavo di avere il lettore difettoso, il problema sembra effettivamente essere un timeout ma in realtà non è così.
> 
> Non sono un esperto quindi potrei star dicendo cazzate, ma questa è la storia: -Avevo già questo lettore nfc in ufficio per impostare i tag di accesso e quando provavo ad usarlo per la cie ottenevo effettivamente un errore in timeout con relativo popup sull'app. Mi sono fatto lo spid, e alla fine non sono andato a perdere ulteriore tempo. -2 giorni fa ho avuto bisogno di acquistare un secondo lettore, identico, e "certificato" per la cie, stesso problema.
> 
> A questo punto contatto il mio amico e mi da un consiglio vitale. Cioè di mettere la carta sul lettore in orizzontale. E ora funziona perfettamente sia con il vecchio che con quello appena comprato.
> 
> Normalmente verrebbe da metterlo in queste posizioni: ![immagine](https://user-images.githubusercontent.com/62725689/146060506-c8ab3f34-4e09-4c07-8c8a-97c3993a858d.png)
> 
> In realtà, visto che le posizioni di contatto degli nfc non sono le stesse rispetto allo standard (PRESUMO) se si mette la cara in QUESTA ESATTA POSIZIONE, funziona perfettamente.
> 
> ![immagine](https://user-images.githubusercontent.com/62725689/146060792-457a471a-8f3e-4a2a-80ef-622a1fce031b.png)
> 
> Sono curioso di sapere se è stato un caso o anche agli altri con lo stesso problema questo trucco funzioni.

sei un genio, funziona davvero
